apiVersion: v1
kind: Service
metadata:
  name: {{ include "student-service.fullname" . }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: {{.Values.service.healthCheck}}
  labels:
    {{- include "student-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "student-service.selectorLabels" . | nindent 4 }}
