apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "dbsecret"
        objectType: "secretsmanager"
        jmesPath:
          - path: SPRING_DATASOURCE_URL
            objectAlias: dbUrl
          - path: SPRING_DATASOURCE_USERNAME
            objectAlias: dbUser
          - path: SPRING_DATASOURCE_PASSWORD
            objectAlias: dbPassword
          - path: SPRING_DATASOURCE_DRIVER_CLASSNAME
            objectAlias: dbDriverClass
          - path: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
            objectAlias: dbDialect
  # Create k8s secret. It requires volume mount first in the pod and then sync.
  secretObjects:
    - secretName: dbsecret
      type: Opaque
      data:
        #- objectName: <objectName> or <objectAlias>
        - objectName: dbUrl
          key: db_url
        - objectName: dbUser
          key: db_user
        - objectName: dbPassword
          key: db_password
        - objectName: dbDriverClass
          key: db_driver_class
        - objectName: dbDialect
          key: db_dialect